Config { font = "xft:MetaBookLFC:size=10:antialias=true"
    , additionalFonts = []
    , borderColor = "#333333"
    , border = BottomB
    , bgColor = "#333333"
    , fgColor = "#cccccc"
    , alpha = 255
    , position = Static { xpos = 380, ypos = 0, width = 986, height = 20 }
    , textOffset = 15
    , iconOffset = -1
    , lowerOnStart = True
    , pickBroadest = False
    , persistent = False
    , hideOnStart = False
    , iconRoot = "."
    , allDesktops = False
    , overrideRedirect = True
    , commands = [ Run Weather "UIII" [ "-t","<station>: <tempC> °C, <windMs> m/s",
                                        "-L","18","-H","25",
                                        "--normal","green",
                                        "--high","red",
                                        "--low","lightblue"] 12000
                 , Run Network "wlp2s0" [ "-t","<icon=/home/valentin/.xmonad/dzen2/net_up_03.xbm/><rx>KB/<icon=/home/valentin/.xmonad/dzen2/net_down_03.xbm/><tx>KB"
                                        ] 10
                 , Run Cpu [ "-t", "<icon=/home/valentin/.xmonad/dzen2/cpu.xbm/><total>%"
                           , "-p", "3"
                           , "-m", "0"
                           , "-M", "10"
                           , "-L", "10"
                           , "-H", "50"
                           , "--normal", "#00aa00"
                           , "--high", "red"
                           ] 10
                 , Run Memory ["-t","<icon=/home/valentin/.xmonad/dzen2/mem.xbm/><usedratio>%"
                              , "-p", "3"] 5
                 , Run Swap ["-t", "<icon=/home/valentin/.xmonad/dzen2/swap.xbm/><usedratio>%"
                            , "-w", "4"
                            ] 5
                 , Run Date "%a %_d %b %H:%M" "date" 600
                 , Run DiskIO [("sda", "R:<read>   W:<write>")] ["-L","5000","-H","12000"
                              , "--normal", "#00aa00"
                              , "--high", "red"
                              ] 20
                 ]
    , sepChar = "%"
    , alignSep = "}{"
    , template = "}{ %UIII%  <fc=#ee9a00>%date%</fc>  "
}
